# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FBADKXDX9RljKsjOPz0505pUeUq5CT0P
"""

#1
name = input("What is your first name? ")

#2
print("Hello, " + name + "!")
print("Hola, " + name + "!")
print("Ciao, " + name + "!")

#3
age = input("How many years old are you? ")
print("You are at least " + str(365 * int(age)) + " days old.")

#4
#5
numCourses = input("How many courses are you taking this module? ")
print("You are in class at least " + str(1.75 * 5 * float(numCourses)) + " hours per week.")

#6
#7
tempInFahrenheit = input("What is your body tempature in degrees Fahrenheit? ")
btempInCelsius = 5 / 9 * (float(tempInFahrenheit) - 32)
print("Your body tempature in degrees Celsiues is " + str(btempInCelsius))

#8
#9
tempInCelsius = input("What is the outside tempatrue in degrees Celsius where you currently live? ")
print("The outside tempature where you currently live is " + str(9 / 5 * float(tempInCelsius) + 32) + " degrees Farenheit.")

#10
favQuote = input("What is your favorite quote? ")
author = input("Who is the quote attributed to? ")
print("The number of characters in your favorite quote by " + author + " is " + str(len(favQuote)) + ".")

