# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ySuRtN5aiIK6MS8JGT0zw8WvGsFvT2Mk
"""

def concat(x, y, z):
  result = str(x) + " and " + str(y) + " is " + str(z)
  return result

def add(x, y):
  result = int(x) + int(y)
  return result

def showOutput(x, y):
  result = add(x, y)
  result = concat(x, y, result)
  print("The sum of " + result + ".")

def playGame():
  n1 = input("Give me an integer: ")
  n2 = input("Give me another integer: ")
  nT = int(n1) + int(n2)
  showOutput(n1, n2)
  n1 = add(n1, n2)
  nT = nT + n1
  showOutput(n2, n1)
  n2 = add(n1, n2)
  nT = nT + n2
  showOutput(n1, n2)
  n1 = add(n1, n2)
  nT = nT + n1
  showOutput(n2, n1)
  n2 = add(n1, n2)
  nT = nT + n2
  showOutput(n1, n2)
  n1 = add(n1, n2)
  n5 = n1
  nT = nT + n1
  showOutput(n2, n1)
  n2 = add(n1, n2)
  nT = nT + n2
  showOutput(n1, n2)
  n1 = add(n1, n2)
  nT = nT + n1
  showOutput(n2, n1)
  n2 = add(n1, n2)
  nT = nT + n2
  print("The total sum of the two given numbers and all those sums is " + \
        str(nT) + ".")
  print("That total sum divided by the fifth sum is " + \
        str(int(nT / n5)) + ".")

playGame()



